### ISSUE TITLE
Ghosts: Configurability for which windows leaves ghosts

### ISSUE THREAD

**Issue by BackOrder** [redhog/InfiniteGlass#33] opened 2020-02-18 21:30 UTC
![image](https://user-images.githubusercontent.com/8844578/74779629-d9f65800-526b-11ea-837e-da4cb6e61440.png)

Even xkill can't do the job. Then I quit and reopen the WM and they come back.

**Comment by redhog** [comment] 2020-02-19 10:14
Wait, WINDOWS+C doesn't kill them? I mean, windows are supposed to leave shadows, where they can reappear if a window  with the same name is opened, but you're supposed to be able to close shadows too!

**Comment by BackOrder** [comment] 2020-02-19 16:04
WINDOWS+C is working. The problem is the shadow remains when I exit applications. Then I tried xkill, shadow still remains. WINDOWS+C did remove the shadows though.

**Comment by redhog** [comment] 2020-02-19 16:21
So the idea is that:

* You can save an app using WIN+S. If the app does not support saving, it just exits, closing all its windows.
* You can close a window using WIN+C.
* All windows will leave a ghost window when they are closed. If they are connected to an app that supports saving, clicking on them will restart the app,
* Ghosts can be closed, that is, deleted, using WIN+C.

Not sure how to document this better / where to document it?

Also,a bit strange xkill didn't work.It should possibly have killed your whole session... ghost windows are owned by the session manager (glass-ghosts), and everything else is a child process of the session manager...

**Comment by BackOrder** [comment] 2020-02-19 16:28
> Not sure how to document this better / where to document it?

You just did! There should be a section in the documentation to outline (like what you wrote above) the intended workflow because your WM has a different paradigm than other WMs. Let's just say a Windows user would be totally lost. You know?

> Also,a bit strange xkill didn't work.It should possibly have killed your whole session... ghost windows are owned by the session manager (glass-ghosts), and everything else is a child process of the session manager...

That would deserve investigation. At least, perhaps, when you exit a window without saving its state, it should also close the shadow. That would be a behaviour that makes sense to me.

**Comment by redhog** [comment] 2020-02-19 16:32
Well, not leaving a ghost for apps that don't support saving makes a lot of apps less usable, as they'll always appear in the current view, wherever that is, and you can't use them to build workspaces... But I'll try really hard to write wrappers and hacks to make all apps savable...

I guess I could make this configurable if it annoys you, but I never found "double click WIN+C" to be too annoying... I did spend some time to try to make popups not leave ghosts thou. Could possibly spend some more time on that?

**Comment by redhog** [comment] 2020-02-19 16:33
Also, maybe bind ALT+F4 to close, not just WIN+C?

**Comment by BackOrder** [comment] 2020-02-19 16:36
Hmmm. It's difficult to know because I don't have as much time spent with the WM as you do. Perhaps you could record video that will show the normal workflow on how you use the WM? WIN+C is actually fine. It's just strange when you type exit in the xterm, or File > Exit in an app, and the shadow remains.

**Comment by redhog** [comment] 2020-02-19 16:41
yeah, I guess that's a bit surprising. But the window content is replaced with the sleeping symbol, right (just checking)?

Also documented this here: https://redhog.github.io/InfiniteGlass/docs/SESSION.html

**Comment by BackOrder** [comment] 2020-02-19 16:52
> yeah, I guess that's a bit surprising. But the window content is replaced with the sleeping symbol, right (just checking)?

Open and moved Audacity:
![image](https://user-images.githubusercontent.com/8844578/74854863-e7fcb500-530d-11ea-862f-fcb88bb90f95.png)

Exit (or WIN-S, I suppose):
![image](https://user-images.githubusercontent.com/8844578/74854933-fea30c00-530d-11ea-9b97-3bafd2abc412.png)

Double click on the sleeping window doesn't work.

> Also documented this here: https://redhog.github.io/InfiniteGlass/docs/SESSION.html

Thank you. I think that I'm getting the workflow a bit better now.

**Comment by redhog** [comment] 2020-02-19 17:21
So Audacity Says "No state saved", which means you can't click to restart. If you restart audacity it will reappear in the same spot though. Maybe I should make this difference more obvious some how? I could have a different icon (sleeping in bed vs grave stone maybe?). Would that help do you think?

**Comment by redhog** [comment] 2020-02-19 17:22
Also, exit is not necessarily WIN+S, depends on the app. WIN+S is what happens happens to an app under a "normal" desktop when you log out...

**Comment by redhog** [comment] 2020-02-19 17:23
This btw is super good feedback - polishing the UX of this is super important to make the whole thing practical...

**Comment by BackOrder** [comment] 2020-02-19 19:14
> This btw is super good feedback - polishing the UX of this is super important to make the whole thing practical...

Oh! I'm glad that it's useful. I play around your WM about 20 minutes per day. Very modest contribution here.

What app should I install that support states? It would be useful during tests in order to compare behaviour. 

> Maybe I should make this difference more obvious some how? I could have a different icon (sleeping in bed vs grave stone maybe?). Would that help do you think?

Grave stone would be a good idea but it still seem to me that it should just be removed. Also, did you noticed that opening Audacity first create a sleeping shadow (you can only see it after moving Audacity) and then quitting creates a second one.

**Comment by redhog** [comment] 2020-02-19 19:19
I use Pluma, the text editor from the MATE desktop env. as a good test tool.
You can also use emacs or Chrome with the config described under https://redhog.github.io/InfiniteGlass/docs/INTEGRATIONS.html

Hm, the small shadow to the left? That's possibly a shadow after some kind of splash screen? That is indeed annoying, and I'll see if I can make splash screens to not generate shadows...

**Comment by BackOrder** [comment] 2020-02-19 19:32
And the winner is... Pluma! Saving works, double click works, still the annoying little shadow.

![image](https://user-images.githubusercontent.com/8844578/74868619-8ac02e00-5324-11ea-8cd9-53e7b6a53770.png)

Double clicking doesn't bring Pluma back with the file notes.txt. Is that the expected behaviour? I would have thought the whole point of saving is more than just bring back an app to life.

**Comment by redhog** [comment] 2020-02-19 19:56
Yep, it should bring back the file you had open....  And it does for me... 
Tiny shadow I'll need to try to reproduce. When does it appear exactly?
Also, it should be enough to single-click...

**Comment by redhog** [comment] 2020-02-19 19:58
Just tested pluma again, and it works as it should:

Start pluma.
Write some text.
Save document under some name.
Press WIN+S
Click on the shadow that apears.
Pluma comes up with the same file open.

**Comment by BackOrder** [comment] 2020-02-19 20:05
[notes-20200219-1505.txt](https://github.com/redhog/InfiniteGlass/files/4227191/notes-20200219-1505.txt)

**Comment by redhog** [comment] 2020-02-19 20:16
Oh.... it's probably because there's no dbus inside docker, and pluma, being MATE/GNOME needs dbus to do anything....

Not sure how hard it is to get dbus up and running inside docker. Hm...

**Comment by BackOrder** [comment] 2020-02-19 20:20
dbus is already installed but it's not running as a service.

**Comment by redhog** [comment] 2020-02-19 20:25
Yeah, I guess pluma wants to connect to it... Running more a real desktop setup inside docker is a bit tricky. Do you have dbus on your system outside docker?

**Comment by BackOrder** [comment] 2020-02-19 20:29
> Yeah, I guess pluma wants to connect to it... Running more a real desktop setup inside docker is a bit tricky. Do you have dbus on your system outside docker?

It should be possible to setup docker to do that. I do have dbus outside docker.

**Comment by redhog** [comment] 2020-02-19 20:30
Just dug a bit... it's hairy, because dbus isn't just one socket. And the socket paths are spread out all over... See https://github.com/mviereck/x11docker/wiki/How-to-connect-container-to-DBus-from-host

**Comment by BackOrder** [comment] 2020-02-20 00:24
This should be working after installing **dbus-x11** and fix `/home/glass/.conf` because it is owned by root:root, instead of glass:glass (or glass:users).

**Comment by redhog** [comment] 2020-02-20 09:47
It does! Awesome! I'm pushing a fixed version of the Dockerfile as I'm writing this :)

**Comment by redhog** [comment] 2020-02-20 12:55
Also https://github.com/redhog/InfiniteGlass/commit/799d8d28454da4bb1af4b32c666ef11227a4684c contains a bugfix for popups and splash windows to not leave shadows, as that is nearly never useful...

**Comment by redhog** [comment] 2020-02-20 12:59
I'm unsure if windows with _NET_WM_WINDOW_TYPE=_NET_WM_WINDOW_TYPE_DIALOG shoudl lack shadows - for e.g. file open they're quite annoying, but for toolboxes of say GIMP it's very useful... esp in multiwindow mode...

**Comment by BackOrder** [comment] 2020-02-20 13:12
> I'm unsure if windows with _NET_WM_WINDOW_TYPE=_NET_WM_WINDOW_TYPE_DIALOG shoudl lack shadows - for e.g. file open they're quite annoying, but for toolboxes of say GIMP it's very useful... esp in multiwindow mode...

Earlier I suggested to add window decorations that include minimize, maximize and close but also settings (cog). We could customize such things on per app basis. Default would close them.

**Comment by redhog** [comment] 2020-02-20 13:24
Hm, that is an interesting possibility, to provide som kind of "pin" to individual windows or apps to turn on/off shadows for windows...

I'd much rather have the default depend on the type of window (and be on for the main app window), but the config option for apps that behave a bit differently is very interesting.

I'll need to build proper window decorations with buttons, which is something I don't currently have...

**Comment by BackOrder** [comment] 2020-02-20 13:39
You could take a look at https://www.flaticon.com/ and see what you like. I will get you the licenses for those. :)

**Comment by redhog** [comment] 2020-02-20 13:47
Hm, so not creative commons?

**Comment by BackOrder** [comment] 2020-02-20 13:52
Either way is fine. It's really up to you!

**Comment by BackOrder** [comment] 2020-02-20 14:21
Perhaps you should take a look at icons packs. Some of them have a couple hundred icons. It would ensure consistency. See if you like something.

**Comment by redhog** [comment] 2020-03-11 09:59
Solved in https://github.com/redhog/InfiniteGlass/pull/62, use the save-icon to toggle

**Closed by redhog** 2020-03-11 09:59 UTC
